language: java
before_script: cd 12f_app
script: mvn clean install
deploy:
  edge: true
  provider: cloudfoundry
  username: Silva28 
  api: https://api.run.pivotal.io
  organization: works
  space: development
